root = "."
tmp_dir = "/app/tmp"

[build]
bin = "./tmp/main"

[log]
log_level = "info"
log_file = "/app/tmp/air.log"

[[watcher]]
paths = [
  "**/*.go",
  "**/*.html",
  "**/*.tmpl",
  "**/*.css",
  "**/*.js"
]
exclude_paths = []
