root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"
# build_dir = "bin"

[build]
# cmd = "go build -o tmp/bin/main"
# watch = ["*.go", "go.mod", "go.sum"]
# bin = "./tmp/bin/main"

  args_bin = []
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main ."
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[run]
exec = "./tmp/bin/main"
watch = ["tmp/bin/main"]

[log]
log_level = "info"
log_file = "/app/tmp/air.log"

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false

[[watcher]]
paths = [
  "**/*.go",
  "**/*.html",
  "**/*.tmpl",
  "**/*.css",
  "**/*.js"
]
exclude_paths = []
