version: '3'
services:
  api:
    container_name: goapi
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    container_name: godb
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: gorestuser
      POSTGRES_PASSWORD: gorestpass
      POSTGRES_DB: gorestdevelopment
volumes:
  db-data:
